# Generated by Django 6.0.5 on 2026-07-14 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_available',
            field=models.BooleanField(default=True, help_text='آیا کارشناس برای پذیرش پرونده جدید در دسترس است؟', verbose_name='در دسترس'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_concurrent',
            field=models.PositiveIntegerField(default=5, help_text='فقط برای کارشناسان', verbose_name='حداکثر پرونده\u200cهای همزمان'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral',
            field=models.ForeignKey(blank=True, help_text='کاربری که این فرد زیر نظر او کار می\u200cکند.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subordinates', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست'),
        ),
    ]
