# Generated by Django 6.0.5 on 2026-06-30 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('dynamicform', '0002_remove_forminput_options_fieldoption'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FormInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام فرم کپی')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان فرم کپی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('custom_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام اختصاصی')),
                ('deadline_days', models.PositiveIntegerField(default=1, help_text='0 = بدون محدودیت زمانی', verbose_name='زمان مهلت (روز)')),
                ('status', models.CharField(choices=[('draft', 'پیش\u200cنویس'), ('in_progress', 'در حال تکمیل'), ('waiting', 'در انتظار'), ('overdue', 'تاخیر داشته'), ('completed', 'تکمیل شده'), ('approved', 'تایید شده'), ('rejected', 'رد شده'), ('canceled', 'لغو شده')], default='draft', max_length=20, verbose_name='وضعیت')),
                ('current_step_number', models.PositiveIntegerField(default=1, verbose_name='شماره مرحله فعلی')),
                ('step_started_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان شروع مرحله فعلی')),
                ('step_deadline', models.DateTimeField(blank=True, null=True, verbose_name='مهلت مرحله فعلی')),
                ('step_history', models.JSONField(blank=True, default=list, verbose_name='تاریخچه مراحل')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان شروع')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل')),
                ('overdue_count', models.PositiveIntegerField(default=0, verbose_name='تعداد تاخیرها')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_forms', to=settings.AUTH_USER_MODEL, verbose_name='اختصاص داده شده به')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_forms', to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
                ('original_template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instances', to='dynamicform.formtemplate', verbose_name='نمونه فرم اصلی')),
            ],
            options={
                'verbose_name': 'فرم در حال اجرا',
                'verbose_name_plural': 'فرم\u200cهای در حال اجرا',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='InstanceField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='نام فیلد')),
                ('field_title', models.CharField(max_length=200, verbose_name='عنوان فیلد')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('step_number', models.PositiveIntegerField(default=1, verbose_name='شماره مرحله')),
                ('is_required', models.BooleanField(default=False, verbose_name='اجباری')),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True, verbose_name='متن راهنما')),
                ('help_text', models.TextField(blank=True, null=True, verbose_name='راهنمای تکمیلی')),
                ('default_value', models.TextField(blank=True, null=True, verbose_name='مقدار پیش\u200cفرض')),
                ('min_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداقل طول')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر طول')),
                ('min_value', models.IntegerField(blank=True, null=True, verbose_name='حداقل مقدار')),
                ('max_value', models.IntegerField(blank=True, null=True, verbose_name='حداکثر مقدار')),
                ('max_file_size', models.PositiveIntegerField(default=5, verbose_name='حداکثر حجم (مگابایت)')),
                ('allowed_extensions', models.CharField(blank=True, help_text='مثال: .pdf,.doc,.docx یا .jpg,.png,.gif', max_length=500, null=True, verbose_name='پسوندهای مجاز')),
                ('access_type', models.CharField(choices=[('all', 'همه کاربران'), ('specific_role', 'نقش خاص'), ('specific_user', 'شخص خاص')], default='all', max_length=20, verbose_name='نوع دسترسی')),
                ('field_deadline', models.DateTimeField(blank=True, help_text='اگر خالی باشد، از مهلت کل فرم استفاده می\u200cشود', null=True, verbose_name='مهلت این فیلد')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('allowed_roles', models.ManyToManyField(blank=True, to='account.role', verbose_name='نقش\u200cهای مجاز')),
                ('allowed_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز')),
                ('form_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='form_flow.forminstance', verbose_name='فرم کپی')),
                ('original_input', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='dynamicform.forminput', verbose_name='فیلد اصلی')),
            ],
            options={
                'verbose_name': 'فیلد فرم کپی',
                'verbose_name_plural': 'فیلدهای فرم کپی',
                'ordering': ['step_number', 'order'],
                'unique_together': {('form_instance', 'field_name')},
            },
        ),
        migrations.CreateModel(
            name='FormFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(blank=True, null=True, verbose_name='مقدار متنی')),
                ('file_value', models.FileField(blank=True, null=True, upload_to='form_files/%Y/%m/%d/', verbose_name='فایل')),
                ('image_value', models.ImageField(blank=True, null=True, upload_to='form_images/%Y/%m/%d/', verbose_name='تصویر')),
                ('filled_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان پر کردن')),
                ('filled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='پر شده توسط')),
                ('form_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_values', to='form_flow.forminstance', verbose_name='فرم کپی')),
                ('instance_field', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_values', to='form_flow.instancefield', verbose_name='فیلد کپی')),
            ],
            options={
                'verbose_name': 'مقدار فیلد',
                'verbose_name_plural': 'مقادیر فیلدها',
                'ordering': ['instance_field__step_number', 'instance_field__order'],
                'unique_together': {('form_instance', 'instance_field')},
            },
        ),
        migrations.CreateModel(
            name='InstanceFieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='کلید')),
                ('value', models.CharField(max_length=200, verbose_name='مقدار نمایشی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('instance_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_options', to='form_flow.instancefield', verbose_name='فیلد کپی')),
            ],
            options={
                'verbose_name': 'گزینه فیلد کپی',
                'verbose_name_plural': 'گزینه\u200cهای فیلد کپی',
                'ordering': ['order'],
                'unique_together': {('instance_field', 'key')},
            },
        ),
    ]
