# Generated by Django 6.0.5 on 2026-06-30 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_flow', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instancefield',
            name='field_deadline',
        ),
        migrations.AddField(
            model_name='instancefield',
            name='field_deadline_hours',
            field=models.PositiveIntegerField(default=0, help_text='0 = بدون محدودیت (از مهلت مرحله استفاده می\u200cشود)', verbose_name='مهلت این فیلد (ساعت)'),
        ),
        migrations.AlterField(
            model_name='forminstance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='forminstance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='instancefield',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='instancefield',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
