# Generated by Django 6.0.5 on 2026-07-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_flow', '0004_alter_usernotification_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forminstance',
            name='deadline_days',
        ),
        migrations.AddField(
            model_name='forminstance',
            name='deadline_hours',
            field=models.PositiveIntegerField(default=1, help_text='0 = بدون محدودیت زمانی', verbose_name='زمان مهلت (ساعت)'),
        ),
    ]
