# Generated by Django 6.0.5 on 2026-07-05 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_flow', '0005_remove_forminstance_deadline_days_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forminstance',
            name='deadline_hours',
            field=models.PositiveIntegerField(default=24, help_text='0 = بدون محدودیت زمانی', verbose_name='زمان مهلت (ساعت)'),
        ),
    ]
