# Generated by Django 6.0.5 on 2026-07-06 16:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form_flow', '0006_alter_forminstance_deadline_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='forminstance',
            name='is_rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forminstance',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forminstance',
            name='rejected_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejected_forms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forminstance',
            name='rejection_level',
            field=models.CharField(blank=True, choices=[('field', 'فیلد'), ('step', 'مرحله'), ('form', 'کل فرم')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='forminstance',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forminstance',
            name='total_rejections',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
