# Generated by Django 6.0.5 on 2026-06-30 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InputTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_type', models.CharField(choices=[('text', 'متن کوتاه'), ('textarea', 'متن بلند'), ('number', 'عدد'), ('email', 'ایمیل'), ('phone', 'تلفن'), ('date', 'تاریخ'), ('datetime', 'تاریخ و زمان'), ('time', 'ساعت'), ('select', 'انتخاب از لیست'), ('checkbox', 'چک\u200cباکس'), ('radio', 'دکمه رادیویی'), ('file', 'فایل'), ('image', 'تصویر'), ('url', 'لینک'), ('color', 'رنگ'), ('password', 'رمز عبور')], max_length=20, unique=True, verbose_name='نوع اینپوت')),
                ('css_class', models.CharField(blank=True, max_length=200, null=True, verbose_name='کلاس CSS')),
                ('wrapper_class', models.CharField(blank=True, max_length=200, null=True, verbose_name='کلاس کانتینر')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'نمونه اینپوت',
                'verbose_name_plural': 'نمونه اینپوت\u200cها',
            },
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='نام فرم')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان نمایشی')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('allowed_roles', models.ManyToManyField(blank=True, related_name='accessible_forms', to='account.role', verbose_name='نقش\u200cهای مجاز برای استفاده از فرم')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='ایجاد شده توسط')),
            ],
            options={
                'verbose_name': 'فرم نمونه',
                'verbose_name_plural': 'فرم\u200cهای نمونه',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FormInput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='نام فیلد')),
                ('field_title', models.CharField(max_length=200, verbose_name='عنوان فیلد')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('step_number', models.PositiveIntegerField(default=1, help_text='این فیلد در کدام مرحله باید پر شود؟ (همه فیلدهای با شماره یکسان، همزمان نمایش داده می\u200cشوند)', verbose_name='شماره مرحله')),
                ('is_required', models.BooleanField(default=False, verbose_name='اجباری')),
                ('placeholder', models.CharField(blank=True, max_length=200, null=True, verbose_name='متن راهنما')),
                ('help_text', models.TextField(blank=True, null=True, verbose_name='راهنمای تکمیلی')),
                ('default_value', models.TextField(blank=True, null=True, verbose_name='مقدار پیش\u200cفرض')),
                ('options', models.JSONField(blank=True, null=True, verbose_name='گزینه\u200cها')),
                ('min_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداقل طول')),
                ('max_length', models.PositiveIntegerField(blank=True, null=True, verbose_name='حداکثر طول')),
                ('min_value', models.IntegerField(blank=True, null=True, verbose_name='حداقل مقدار')),
                ('max_value', models.IntegerField(blank=True, null=True, verbose_name='حداکثر مقدار')),
                ('max_file_size', models.PositiveIntegerField(default=5, verbose_name='حداکثر حجم (مگابایت)')),
                ('allowed_extensions', models.CharField(blank=True, help_text='مثال: .pdf,.doc,.docx یا .jpg,.png,.gif', max_length=500, null=True, verbose_name='پسوندهای مجاز')),
                ('access_type', models.CharField(choices=[('all', 'همه کاربران'), ('specific_role', 'نقش خاص'), ('specific_user', 'شخص خاص')], default='all', max_length=20, verbose_name='نوع دسترسی')),
                ('allowed_roles', models.ManyToManyField(blank=True, to='account.role', verbose_name='نقش\u200cهای مجاز')),
                ('allowed_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='کاربران مجاز')),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dynamicform.formtemplate', verbose_name='فرم')),
                ('input', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dynamicform.inputtemplate', verbose_name='نوع اینپوت')),
            ],
            options={
                'verbose_name': 'فیلد فرم',
                'verbose_name_plural': 'فیلدهای فرم',
                'ordering': ['step_number', 'order'],
                'unique_together': {('form', 'field_name')},
            },
        ),
        migrations.AddField(
            model_name='formtemplate',
            name='inputs',
            field=models.ManyToManyField(related_name='forms', through='dynamicform.FormInput', to='dynamicform.inputtemplate', verbose_name='اینپوت\u200cها'),
        ),
    ]
