# Generated by Django 6.0.5 on 2026-06-30 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamicform', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forminput',
            name='options',
        ),
        migrations.CreateModel(
            name='FieldOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='کلید')),
                ('value', models.CharField(max_length=200, verbose_name='مقدار نمایشی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('form_input', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_options', to='dynamicform.forminput')),
            ],
            options={
                'verbose_name': 'گزینه فیلد',
                'verbose_name_plural': 'گزینه\u200cهای فیلد',
                'ordering': ['order'],
                'unique_together': {('form_input', 'key')},
            },
        ),
    ]
