# Generated by Django 6.0.5 on 2026-07-18 02:41

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('case_management', '0008_alter_customerprocess_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_register_share', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='سهم ثبت\u200cکننده فایل (%)')),
                ('customer_register_share', models.DecimalField(decimal_places=2, default=5.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='سهم ثبت\u200cکننده مشتری (%)')),
                ('expert_share', models.DecimalField(decimal_places=2, default=20.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='سهم کارشناس (%)')),
                ('supervisor_share', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='سهم سرپرست (%)')),
                ('meeting_manager_share', models.DecimalField(decimal_places=2, default=10.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='سهم مدیر جلسه (%)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت تغییرات')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commission_settings_updated', to=settings.AUTH_USER_MODEL, verbose_name='بروزرسانی\u200cکننده')),
            ],
            options={
                'verbose_name': 'تنظیمات کمیسیون',
                'verbose_name_plural': 'تنظیمات کمیسیون',
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی مدارک'), ('documents_reviewed', 'مدارک بررسی شد'), ('contract_drafted', 'پیش\u200cنویس قرارداد آماده'), ('signed_by_customer', 'امضای مشتری'), ('signed_by_other', 'امضای طرف دیگر'), ('completed', 'تکمیل و نهایی شد'), ('cancelled', 'لغو شد')], default='pending', max_length=30, verbose_name='وضعیت قرارداد')),
                ('draft_file', models.FileField(blank=True, null=True, upload_to='contracts/drafts/', verbose_name='فایل پیش\u200cنویس قرارداد')),
                ('signed_file', models.FileField(blank=True, null=True, upload_to='contracts/signed/', verbose_name='فایل امضاشده قرارداد')),
                ('supporting_documents', models.FileField(blank=True, null=True, upload_to='contracts/supporting/', verbose_name='مدارک پشتیبان')),
                ('review_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای واحد قرارداد')),
                ('contract_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای تکمیلی قرارداد')),
                ('signature_date_customer', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ امضای مشتری')),
                ('signature_date_other', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ امضای طرف دیگر')),
                ('finalization_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ نهایی\u200cسازی قرارداد')),
                ('contract_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='شماره قرارداد')),
                ('is_confidential', models.BooleanField(default=False, verbose_name='محرمانه؟')),
                ('contract_officer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts_handled', to=settings.AUTH_USER_MODEL, verbose_name='مسئول قرارداد')),
                ('process', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contract', to='case_management.customerprocess', verbose_name='فرآیند مرتبط')),
            ],
            options={
                'verbose_name': 'قرارداد',
                'verbose_name_plural': 'قراردادها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Commission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ کل معامله (تومان)')),
                ('property_register_share', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='سهم ثبت\u200cکننده فایل (%)')),
                ('customer_register_share', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='سهم ثبت\u200cکننده مشتری (%)')),
                ('expert_share', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='سهم کارشناس (%)')),
                ('supervisor_share', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='سهم سرپرست (%)')),
                ('meeting_manager_share', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='سهم مدیر جلسه (%)')),
                ('property_register_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ سهم ثبت\u200cکننده فایل')),
                ('customer_register_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ سهم ثبت\u200cکننده مشتری')),
                ('expert_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ سهم کارشناس')),
                ('supervisor_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ سهم سرپرست')),
                ('meeting_manager_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ سهم مدیر جلسه')),
                ('total_commission', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ کل کمیسیون')),
                ('status', models.CharField(choices=[('pending', 'در انتظار محاسبه'), ('calculated', 'محاسبه شد'), ('partial_paid', 'تسویه ناقص'), ('paid', 'تسویه کامل'), ('cancelled', 'لغو شد')], default='pending', max_length=20, verbose_name='وضعیت تسویه')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تسویه کامل')),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='commissions/receipts/', verbose_name='فایل رسید پرداخت')),
                ('payment_notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای پرداخت')),
                ('accountant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='commissions_handled', to=settings.AUTH_USER_MODEL, verbose_name='حسابدار مسئول')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='commission', to='transaction.contract', verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'کمیسیون',
                'verbose_name_plural': 'کمیسیون\u200cها',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AfterSalesService',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('contact_status', models.CharField(choices=[('pending', 'در انتظار تماس'), ('contacted', 'تماس گرفته شد'), ('follow_up', 'نیاز به پیگیری مجدد'), ('closed', 'بسته شد')], default='pending', max_length=20, verbose_name='وضعیت تماس')),
                ('contact_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ آخرین تماس')),
                ('next_follow_up_date', models.DateTimeField(blank=True, null=True, verbose_name='زمان پیگیری بعدی')),
                ('satisfaction', models.CharField(choices=[('satisfied', 'رضایت\u200cمند'), ('neutral', 'متوسط'), ('unsatisfied', 'ناراضی'), ('not_contacted', 'تماس گرفته نشده')], default='not_contacted', max_length=15, verbose_name='سطح رضایت')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='بازخورد مشتری')),
                ('new_referral', models.BooleanField(default=False, verbose_name='معرفی مشتری جدید؟')),
                ('referral_details', models.TextField(blank=True, null=True, verbose_name='جزئیات معرفی')),
                ('loyal_customer', models.BooleanField(default=False, verbose_name='مشتری وفادار؟')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='یادداشت\u200cهای تکمیلی')),
                ('is_closed', models.BooleanField(default=False, verbose_name='پرونده بسته شد؟')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بسته شدن')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aftersales_handled', to=settings.AUTH_USER_MODEL, verbose_name='مسئول پیگیری')),
                ('contract', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='aftersales', to='transaction.contract', verbose_name='قرارداد')),
            ],
            options={
                'verbose_name': 'خدمات پس از فروش',
                'verbose_name_plural': 'خدمات پس از فروش',
                'ordering': ['-created_at'],
            },
        ),
    ]
