# Generated by Django 6.0.5 on 2026-07-18 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0008_alter_customerprocess_status'),
        ('estate', '0017_match_introduction_confirmed_and_more'),
        ('transaction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='estate.customer', verbose_name='مشتری قرارداد'),
        ),
        migrations.AddField(
            model_name='contract',
            name='property_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='estate.property', verbose_name='ملک قرارداد'),
        ),
        migrations.AddField(
            model_name='contract',
            name='source_visit',
            field=models.ForeignKey(blank=True, help_text='بازدیدی که نتیجه آن به تنظیم قرارداد منجر شد', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_contracts', to='case_management.visit', verbose_name='بازدید منجر به قرارداد'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['customer'], name='transaction_custome_492490_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['property_ref'], name='transaction_propert_74ba8a_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['status'], name='transaction_status_a6629f_idx'),
        ),
    ]
