# Generated by Django 6.0.5 on 2026-07-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0002_contract_customer_contract_property_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='commission_amount',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='اگر خالی باشد، توسط حسابداری محاسبه می\u200cشود', max_digits=15, null=True, verbose_name='مبلغ کمیسیون (تومان)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('sale', 'فروش'), ('rent', 'اجاره'), ('partnership', 'مشارکت در ساخت'), ('investment', 'سرمایه\u200cگذاری')], max_length=20, null=True, verbose_name='نوع قرارداد'),
        ),
        migrations.AddField(
            model_name='contract',
            name='final_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='مبلغ نهایی قرارداد (تومان)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='mortgage_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='مبلغ رهن (تومان)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='rent_amount',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='مبلغ اجاره ماهیانه (تومان)'),
        ),
        migrations.AddField(
            model_name='contract',
            name='rent_end_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پایان اجاره'),
        ),
    ]
