# Generated by Django 6.0.5 on 2026-07-18 22:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0003_contract_commission_amount_contract_contract_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='wallet_transferred_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ واریز به کیف پول'),
        ),
        migrations.AddField(
            model_name='commission',
            name='wallet_transferred_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wallet_transfers', to=settings.AUTH_USER_MODEL, verbose_name='واریزکننده به کیف پول'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار محاسبه'), ('calculated', 'محاسبه شد'), ('wallet_transferred', 'واریز به کیف پول'), ('partial_paid', 'تسویه ناقص'), ('paid', 'تسویه کامل'), ('cancelled', 'لغو شد')], default='pending', max_length=20, verbose_name='وضعیت تسویه'),
        ),
        migrations.CreateModel(
            name='WithdrawalRequest',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('amount', models.PositiveIntegerField(verbose_name='مبلغ درخواستی (تومان)')),
                ('bank_name', models.CharField(max_length=50, verbose_name='نام بانک')),
                ('account_number', models.CharField(max_length=30, verbose_name='شماره حساب')),
                ('card_number', models.CharField(max_length=16, verbose_name='شماره کارت')),
                ('sheba_number', models.CharField(max_length=50, verbose_name='شماره شبا')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('approved', 'تایید شده'), ('paid', 'پرداخت شد'), ('rejected', 'رد شد')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی')),
                ('payment_receipt', models.FileField(blank=True, null=True, upload_to='withdrawals/receipts/', verbose_name='فایل رسید پرداخت')),
                ('note', models.TextField(blank=True, null=True, verbose_name='یادداشت')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_withdrawals', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL, verbose_name='متقاضی')),
            ],
            options={
                'verbose_name': 'درخواست برداشت',
                'verbose_name_plural': 'درخواست\u200cهای برداشت',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='transaction_user_id_c38cb5_idx'), models.Index(fields=['status'], name='transaction_status_6a9840_idx')],
            },
        ),
    ]
