# Generated by Django 6.0.5 on 2026-07-18 23:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0004_commission_wallet_transferred_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='customer_register_share',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='سهم ثبت\u200cکننده مشتری (%)'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='expert_share',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='سهم کارشناس (%)'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='meeting_manager_share',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='سهم مدیر جلسه (%)'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='property_register_share',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='سهم ثبت\u200cکننده فایل (%)'),
        ),
        migrations.AlterField(
            model_name='commission',
            name='supervisor_share',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='سهم سرپرست (%)'),
        ),
        migrations.AlterField(
            model_name='commissionsetting',
            name='customer_register_share',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='سهم ثبت\u200cکننده مشتری (%)'),
        ),
        migrations.AlterField(
            model_name='commissionsetting',
            name='expert_share',
            field=models.PositiveIntegerField(default=20, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='سهم کارشناس (%)'),
        ),
        migrations.AlterField(
            model_name='commissionsetting',
            name='meeting_manager_share',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='سهم مدیر جلسه (%)'),
        ),
        migrations.AlterField(
            model_name='commissionsetting',
            name='property_register_share',
            field=models.PositiveIntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='سهم ثبت\u200cکننده فایل (%)'),
        ),
        migrations.AlterField(
            model_name='commissionsetting',
            name='supervisor_share',
            field=models.PositiveIntegerField(default=10, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='سهم سرپرست (%)'),
        ),
    ]
