# Generated by Django 6.0.5 on 2026-07-19 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_commission_customer_register_share_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commission',
            name='total_share_sum',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='جمع سهم\u200cهای پرداختی به اعضا'),
        ),
    ]
