# Generated by Django 6.0.5 on 2026-07-19 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0006_commission_total_share_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commission',
            name='total_commission',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='مبلغ کل کمیسیون (دریافتی از طرفین)'),
        ),
    ]
