# Generated by Django 6.0.5 on 2026-07-19 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_alter_commission_total_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='aftersalesservice',
            name='feedback_owner',
            field=models.TextField(blank=True, null=True, verbose_name='بازخورد مالک فایل'),
        ),
        migrations.AddField(
            model_name='aftersalesservice',
            name='satisfaction_owner',
            field=models.CharField(choices=[('satisfied', 'رضایت\u200cمند'), ('neutral', 'متوسط'), ('unsatisfied', 'ناراضی'), ('not_contacted', 'تماس گرفته نشده')], default='not_contacted', max_length=15, verbose_name='رضایت مالک فایل'),
        ),
        migrations.AlterField(
            model_name='aftersalesservice',
            name='satisfaction',
            field=models.CharField(choices=[('satisfied', 'رضایت\u200cمند'), ('neutral', 'متوسط'), ('unsatisfied', 'ناراضی'), ('not_contacted', 'تماس گرفته نشده')], default='not_contacted', max_length=15, verbose_name='رضایت مشتری'),
        ),
    ]
