# Generated by Django 6.0.5 on 2026-07-11 11:31

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='نام شهر')),
                ('code', models.CharField(blank=True, max_length=5, null=True, verbose_name='کد شهر')),
                ('center_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='عرض جغرافیایی مرکز')),
                ('center_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='طول جغرافیایی مرکز')),
            ],
            options={
                'verbose_name': 'شهر',
                'verbose_name_plural': 'شهرها',
                'ordering': ['province__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PropertyType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام نوع ملک')),
                ('code', models.CharField(help_text='مثال: APARTMENT, VILLA, LAND', max_length=20, unique=True, verbose_name='کد نوع ملک')),
                ('icon', models.CharField(blank=True, help_text='نام کلاس آیکون (مثلاً fa-building)', max_length=50, null=True, verbose_name='آیکون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'نوع ملک',
                'verbose_name_plural': 'انواع ملک',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نام استان')),
                ('code', models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='کد استان')),
            ],
            options={
                'verbose_name': 'استان',
                'verbose_name_plural': 'استان\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='نام محله')),
                ('center_latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='عرض جغرافیایی مرکز')),
                ('center_longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='طول جغرافیایی مرکز')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='neighborhoods', to='estate.city', verbose_name='شهر')),
            ],
            options={
                'verbose_name': 'محله',
                'verbose_name_plural': 'محله\u200cها',
                'ordering': ['city__name', 'name'],
                'unique_together': {('city', 'name')},
            },
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cities', to='estate.province', verbose_name='استان'),
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('customer_type', models.CharField(choices=[('buyer', 'خریدار'), ('tenant', 'مستاجر'), ('developer', 'سازنده'), ('investor', 'سرمایه\u200cگذار'), ('all', 'همه موارد')], default='buyer', max_length=20, verbose_name='نوع مشتری')),
                ('status', models.CharField(choices=[('new', 'جدید'), ('assigned', 'ارجاع شده'), ('in_progress', 'در حال بررسی'), ('waiting', 'در انتظار تصمیم'), ('matched', 'تطبیق یافته'), ('purchased', 'خریداری کرده'), ('rented', 'اجاره کرده'), ('inactive', 'غیرفعال')], default='new', max_length=20, verbose_name='وضعیت')),
                ('alternative_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن همراه دوم')),
                ('home_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن منزل')),
                ('work_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='تلفن محل کار')),
                ('job_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='عنوان شغلی')),
                ('company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='نام شرکت')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل بودجه خرید (تومان)')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداکثر بودجه خرید (تومان)')),
                ('rent_type', models.CharField(choices=[('rent', 'اجاره'), ('mortgage', 'رهن'), ('both', 'اجاره و رهن')], default='rent', max_length=20, verbose_name='نوع اجاره')),
                ('mortgage_min', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل رهن (تومان)')),
                ('mortgage_max', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداکثر رهن (تومان)')),
                ('rent_min', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل اجاره ماهیانه (تومان)')),
                ('rent_max', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداکثر اجاره ماهیانه (تومان)')),
                ('min_area', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداقل متراژ')),
                ('max_area', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='حداکثر متراژ')),
                ('min_rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='حداقل اتاق')),
                ('max_rooms', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='حداکثر اتاق')),
                ('requirements', models.JSONField(blank=True, default=dict, help_text="مثال: {'has_parking': True, 'has_elevator': True, 'has_warehouse': False}", verbose_name='نیازهای خاص')),
                ('special_needs', models.TextField(blank=True, null=True, verbose_name='نیازهای ویژه')),
                ('priority', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)], verbose_name='اولویت (۰ تا ۱۰)')),
                ('source', models.CharField(blank=True, help_text='آگهی، معرفی، اینستاگرام، دیوار، سایت', max_length=100, null=True, verbose_name='منبع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('last_contact', models.DateTimeField(blank=True, null=True, verbose_name='آخرین تماس')),
                ('total_interactions', models.PositiveIntegerField(default=0, verbose_name='تعداد کل تعاملات')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده مشتری')),
                ('preferred_cities', models.ManyToManyField(blank=True, related_name='customers_preferred', to='estate.city', verbose_name='شهرهای مورد نظر')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('preferred_neighborhoods', models.ManyToManyField(blank=True, related_name='customers_preferred', to='estate.neighborhood', verbose_name='محله\u200cهای مورد نظر')),
                ('preferred_property_types', models.ManyToManyField(blank=True, related_name='customers_preferred', to='estate.propertytype', verbose_name='انواع ملک مورد نظر')),
            ],
            options={
                'verbose_name': 'مشتری',
                'verbose_name_plural': 'مشتریان',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='estate_cust_user_id_725935_idx'), models.Index(fields=['customer_type', 'status'], name='estate_cust_custome_b6991c_idx'), models.Index(fields=['priority'], name='estate_cust_priorit_581a23_idx'), models.Index(fields=['created_by'], name='estate_cust_created_61db73_idx')],
            },
        ),
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('province', 'name')},
        ),
    ]
