# Generated by Django 6.0.5 on 2026-07-11 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0002_alter_city_code_alter_province_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Requirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: پارکینگ، آسانسور، انباری', max_length=100, unique=True, verbose_name='نام نیاز')),
                ('code', models.CharField(help_text='مثال: PARKING, ELEVATOR, WAREHOUSE', max_length=50, unique=True, verbose_name='کد نیاز')),
                ('icon', models.CharField(blank=True, help_text='نام کلاس آیکون (مثلاً fa-car, fa-elevator)', max_length=50, null=True, verbose_name='آیکون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('category', models.CharField(default='general', help_text='دسته\u200cبندی کلی نیاز (مثلاً: ساختمانی، امنیتی، رفاهی، زیرساخت)', max_length=50, verbose_name='دسته\u200cبندی')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'نیاز خاص',
                'verbose_name_plural': 'نیازهای خاص',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: دیوار، شیپور، اینستاگرام', max_length=100, unique=True, verbose_name='نام منبع')),
                ('code', models.CharField(help_text='مثال: DIVAR, SHIPOUR, INSTAGRAM', max_length=50, unique=True, verbose_name='کد منبع')),
                ('icon', models.CharField(blank=True, help_text='نام کلاس آیکون (مثلاً fa-instagram)', max_length=50, null=True, verbose_name='آیکون')),
                ('color', models.CharField(default='#6c757d', help_text='رنگ HEX برای نمایش در داشبورد (مثلاً #e4405f)', max_length=20, verbose_name='رنگ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('category', models.CharField(default='online', help_text='مثال: آنلاین، شبکه\u200cهای اجتماعی، معرفی، آفلاین', max_length=50, verbose_name='دسته\u200cبندی منبع')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'منبع',
                'verbose_name_plural': 'منابع مشتری',
                'ordering': ['category', 'order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='requirements',
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_requirements',
            field=models.ManyToManyField(blank=True, help_text='امکاناتی که مشتری در ملک مورد نظر خود می\u200cخواهد', related_name='customers_preferred', to='estate.requirement', verbose_name='نیازهای خاص مورد نظر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='source',
            field=models.ForeignKey(blank=True, help_text='منبعی که مشتری از طریق آن به ما معرفی شده است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers', to='estate.source', verbose_name='منبع'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['source'], name='estate_cust_source__4ec25f_idx'),
        ),
    ]
