# Generated by Django 6.0.5 on 2026-07-12 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0003_requirement_source_remove_customer_requirements_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ حذف')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان ملک')),
                ('status', models.CharField(choices=[('available', 'موجود'), ('pending', 'در انتظار'), ('reserved', 'رزرو شده'), ('sold', 'فروخته شده'), ('rented', 'اجاره داده شده'), ('unavailable', 'ناموجود')], default='available', max_length=20, verbose_name='وضعیت')),
                ('contract_type', models.CharField(choices=[('sale', 'فروش'), ('rent', 'اجاره'), ('both', 'فروش و اجاره')], default='sale', max_length=20, verbose_name='نوع قرارداد')),
                ('price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='قیمت فروش (تومان)')),
                ('is_price_negotiable', models.BooleanField(default=False, verbose_name='قیمت توافقی')),
                ('rent_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='اجاره ماهیانه (تومان)')),
                ('mortgage_price', models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='رهن (تومان)')),
                ('is_rent_negotiable', models.BooleanField(default=False, verbose_name='اجاره توافقی')),
                ('area', models.FloatField(verbose_name='متراژ (متر مربع)')),
                ('rooms', models.PositiveSmallIntegerField(default=0, verbose_name='تعداد اتاق')),
                ('floor', models.CharField(blank=True, max_length=20, null=True, verbose_name='طبقه')),
                ('total_floors', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد کل طبقات')),
                ('built_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='سال ساخت')),
                ('is_new_building', models.BooleanField(default=False, verbose_name='نوساز')),
                ('parking_type', models.CharField(choices=[('none', 'بدون پارکینگ'), ('one', 'یک پارکینگ'), ('two', 'دو پارکینگ'), ('three', 'سه پارکینگ'), ('four', 'چهار پارکینگ'), ('more', 'بیشتر از چهار')], default='none', max_length=20, verbose_name='پارکینگ')),
                ('ownership_type', models.CharField(choices=[('owner', 'مالک'), ('tenant', 'مستاجر'), ('manager', 'مدیر'), ('other', 'سایر')], default='owner', max_length=20, verbose_name='نوع مالکیت')),
                ('furnishing_status', models.CharField(choices=[('furnished', 'مبله'), ('semi_furnished', 'نیمه مبله'), ('unfurnished', 'خالی')], default='unfurnished', max_length=20, verbose_name='وضعیت مبلمان')),
                ('address', models.TextField(verbose_name='آدرس دقیق')),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='عرض جغرافیایی')),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True, verbose_name='طول جغرافیایی')),
                ('description', models.TextField(verbose_name='توضیحات کامل')),
                ('short_description', models.CharField(blank=True, max_length=300, null=True, verbose_name='توضیح مختصر')),
                ('contact_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='نام تماس')),
                ('contact_phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس')),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل تماس')),
                ('is_visible', models.BooleanField(default=True, verbose_name='قابل مشاهده')),
                ('is_featured', models.BooleanField(default=False, verbose_name='ویژه')),
                ('is_verified', models.BooleanField(default=False, verbose_name='تایید شده')),
                ('views_count', models.PositiveIntegerField(default=0, verbose_name='تعداد بازدید')),
                ('favorites_count', models.PositiveIntegerField(default=0, verbose_name='تعداد علاقه\u200cمندی\u200cها')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ انتشار')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='estate.city', verbose_name='شهر')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='estate.neighborhood', verbose_name='محله')),
                ('owner_customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_properties', to='estate.customer', verbose_name='مالک ملک')),
                ('property_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='estate.propertytype', verbose_name='نوع ملک')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='estate.province', verbose_name='استان')),
                ('requirements', models.ManyToManyField(blank=True, related_name='properties', to='estate.requirement', verbose_name='امکانات ملک')),
            ],
            options={
                'verbose_name': 'ملک',
                'verbose_name_plural': 'املاک',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'contract_type'], name='estate_prop_status_66df8d_idx'), models.Index(fields=['city', 'neighborhood'], name='estate_prop_city_id_2898bb_idx'), models.Index(fields=['is_visible'], name='estate_prop_is_visi_13c795_idx')],
            },
        ),
    ]
