# Generated by Django 6.0.5 on 2026-07-12 13:36

import django.db.models.deletion
import estate.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0004_property'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='contract_type',
            field=models.CharField(choices=[('sale', 'فروش'), ('rent', 'اجاره'), ('both', 'فروش و اجاره'), ('partnership', 'مشارکت در ساخت'), ('investment', 'جذب سرمایه')], default='sale', max_length=20, verbose_name='نوع قرارداد'),
        ),
        migrations.AlterField(
            model_name='property',
            name='ownership_type',
            field=models.CharField(choices=[('owner', 'مالک'), ('tenant', 'مستاجر'), ('manager', 'مدیر'), ('lawyer', 'وکیل'), ('other', 'سایر')], default='owner', max_length=20, verbose_name='نوع مالکیت'),
        ),
        migrations.CreateModel(
            name='PropertyImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=estate.models.property_image_path, verbose_name='تصویر')),
                ('caption', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_main', models.BooleanField(default=False, help_text='این تصویر به عنوان تصویر اصلی نمایش داده شود', verbose_name='تصویر اصلی')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان آپلود')),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='estate.property', verbose_name='ملک')),
            ],
            options={
                'verbose_name': 'تصویر ملک',
                'verbose_name_plural': 'تصاویر ملک',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PropertyVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_type', models.CharField(choices=[('upload', 'آپلود شده'), ('link', 'لینک خارجی')], default='upload', max_length=10, verbose_name='نوع ویدئو')),
                ('video_file', models.FileField(blank=True, help_text='فایل ویدئو با فرمت\u200cهای mp4, avi, mov', null=True, upload_to=estate.models.property_video_path, verbose_name='فایل ویدئو')),
                ('video_link', models.URLField(blank=True, help_text='لینک ویدئو از سایت\u200cهایی مثل آپارات، یوتیوب، ویمئو', max_length=500, null=True, verbose_name='لینک ویدئو')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to=estate.models.property_video_path, verbose_name='تصویر بندانگشتی')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان ویدئو')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات ویدئو')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_main', models.BooleanField(default=False, verbose_name='ویدئو اصلی')),
                ('duration', models.PositiveIntegerField(blank=True, null=True, verbose_name='مدت زمان (ثانیه)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان آپلود')),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='estate.property', verbose_name='ملک')),
            ],
            options={
                'verbose_name': 'ویدئوی ملک',
                'verbose_name_plural': 'ویدئوهای ملک',
                'ordering': ['order', '-uploaded_at'],
            },
        ),
    ]
