# Generated by Django 6.0.5 on 2026-07-12 13:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0005_alter_property_contract_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('match_score', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز تطابق کلی')),
                ('score_location', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز موقعیت مکانی')),
                ('score_price', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز قیمت')),
                ('score_area', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز متراژ')),
                ('score_rooms', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز تعداد اتاق')),
                ('score_requirements', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز امکانات')),
                ('score_property_type', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز نوع ملک')),
                ('score_contract', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز نوع قرارداد')),
                ('score_rent', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز اجاره/رهن')),
                ('score_ownership', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='امتیاز نوع مالکیت')),
                ('match_type', models.CharField(choices=[('auto', 'خودکار'), ('manual', 'دستی')], default='auto', max_length=10, verbose_name='نوع تطابق')),
                ('match_details', models.JSONField(blank=True, default=dict, help_text='ذخیره جزئیات کامل تطابق به صورت JSON', verbose_name='جزئیات تطابق')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('reviewed', 'بررسی شده'), ('sent', 'ارسال شده به مشتری'), ('interested', 'مشتری علاقه\u200cمند'), ('not_interested', 'مشتری علاقه\u200cمند نیست'), ('visit_done', 'بازدید انجام شده'), ('offered', 'پیشنهاد داده شده'), ('converted', 'تبدیل به معامله'), ('rejected', 'رد شده')], default='pending', max_length=20, verbose_name='وضعیت')),
                ('expert_note', models.TextField(blank=True, null=True, verbose_name='یادداشت کارشناس')),
                ('customer_feedback', models.TextField(blank=True, null=True, verbose_name='بازخورد مشتری')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ ارسال به مشتری')),
                ('viewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ مشاهده توسط مشتری')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی توسط کارشناس')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_created', to=settings.AUTH_USER_MODEL, verbose_name='ثبت\u200cکننده تطابق')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='estate.customer', verbose_name='مشتری')),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='estate.property', verbose_name='ملک')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches_reviewed', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده تطابق')),
            ],
            options={
                'verbose_name': 'تطابق',
                'verbose_name_plural': 'تطابق\u200cها',
                'ordering': ['-match_score', '-created_at'],
                'indexes': [models.Index(fields=['customer', 'status'], name='estate_matc_custome_00870a_idx'), models.Index(fields=['property_ref', 'status'], name='estate_matc_propert_92be30_idx'), models.Index(fields=['match_score'], name='estate_matc_match_s_9f73f5_idx'), models.Index(fields=['status', 'match_score'], name='estate_matc_status_24e13a_idx')],
                'unique_together': {('customer', 'property_ref')},
            },
        ),
    ]
