# Generated by Django 6.0.5 on 2026-07-12 21:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0006_match'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس دقیق'),
        ),
        migrations.AlterField(
            model_name='property',
            name='city',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='estate.city', verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='property',
            name='neighborhood',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='estate.neighborhood', verbose_name='محله'),
        ),
        migrations.AlterField(
            model_name='property',
            name='province',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='estate.province', verbose_name='استان'),
        ),
    ]
