# Generated by Django 6.0.5 on 2026-07-12 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0008_remove_property_owner_customer_property_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='area',
            field=models.FloatField(blank=True, null=True, verbose_name='متراژ (متر مربع)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('sale', 'فروش'), ('rent', 'اجاره'), ('both', 'فروش و اجاره'), ('partnership', 'مشارکت در ساخت'), ('investment', 'جذب سرمایه')], default='sale', max_length=20, null=True, verbose_name='نوع قرارداد'),
        ),
        migrations.AlterField(
            model_name='property',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات کامل'),
        ),
        migrations.AlterField(
            model_name='property',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=15, null=True, verbose_name='قیمت فروش (تومان)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='property_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='estate.propertytype', verbose_name='نوع ملک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='requirements',
            field=models.ManyToManyField(blank=True, null=True, related_name='properties', to='estate.requirement', verbose_name='امکانات ملک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'موجود'), ('pending', 'در انتظار'), ('reserved', 'رزرو شده'), ('sold', 'فروخته شده'), ('rented', 'اجاره داده شده'), ('unavailable', 'ناموجود')], default='available', max_length=20, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='property',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='عنوان ملک'),
        ),
    ]
