# Generated by Django 6.0.5 on 2026-07-12 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0009_alter_property_area_alter_property_contract_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('buyer', 'خریدار'), ('tenant', 'مستاجر'), ('developer', 'سازنده'), ('investor', 'سرمایه\u200cگذار'), ('all', 'همه موارد')], default='buyer', max_length=20, null=True, verbose_name='نوع مشتری'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_cities',
            field=models.ManyToManyField(blank=True, null=True, related_name='customers_preferred', to='estate.city', verbose_name='شهرهای مورد نظر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_neighborhoods',
            field=models.ManyToManyField(blank=True, null=True, related_name='customers_preferred', to='estate.neighborhood', verbose_name='محله\u200cهای مورد نظر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_property_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='customers_preferred', to='estate.propertytype', verbose_name='انواع ملک مورد نظر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_requirements',
            field=models.ManyToManyField(blank=True, help_text='امکاناتی که مشتری در ملک مورد نظر خود می\u200cخواهد', null=True, related_name='customers_preferred', to='estate.requirement', verbose_name='نیازهای خاص مورد نظر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='rent_type',
            field=models.CharField(blank=True, choices=[('rent', 'اجاره'), ('mortgage', 'رهن'), ('both', 'اجاره و رهن')], default='rent', max_length=20, null=True, verbose_name='نوع اجاره'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'جدید'), ('assigned', 'ارجاع شده'), ('in_progress', 'در حال بررسی'), ('waiting', 'در انتظار تصمیم'), ('matched', 'تطبیق یافته'), ('purchased', 'خریداری کرده'), ('rented', 'اجاره کرده'), ('inactive', 'غیرفعال')], default='new', max_length=20, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_profile', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
        ),
    ]
