# Generated by Django 6.0.5 on 2026-07-13 14:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0010_alter_customer_customer_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsageType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='مثال: مسکونی، تجاری، اداری، صنعتی، مختلط، کشاورزی', max_length=50, unique=True, verbose_name='نام کاربری')),
                ('code', models.CharField(help_text='مثال: RESIDENTIAL, COMMERCIAL, OFFICE, INDUSTRIAL, MIXED, AGRICULTURAL', max_length=20, unique=True, verbose_name='کد کاربری')),
                ('icon', models.CharField(blank=True, help_text='نام کلاس آیکون (مثلاً fa-home, fa-store, fa-briefcase)', max_length=50, null=True, verbose_name='آیکون')),
                ('description', models.TextField(blank=True, help_text='توضیحات کامل درباره این نوع کاربری', null=True, verbose_name='توضیحات')),
                ('color', models.CharField(default='#6c757d', help_text='رنگ HEX برای نمایش در داشبورد (مثلاً #4CAF50)', max_length=20, verbose_name='رنگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'نوع کاربری',
                'verbose_name_plural': 'انواع کاربری',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_usage_types',
            field=models.ManyToManyField(blank=True, help_text='کاربری\u200cهایی که مشتری به آنها علاقه دارد', null=True, related_name='customers_preferred', to='estate.usagetype', verbose_name='انواع کاربری مورد نظر'),
        ),
        migrations.AddField(
            model_name='property',
            name='primary_usage',
            field=models.ForeignKey(blank=True, help_text='کاربری اصلی و اولیه این ملک', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_properties', to='estate.usagetype', verbose_name='کاربری اصلی'),
        ),
        migrations.AddField(
            model_name='property',
            name='usage_types',
            field=models.ManyToManyField(blank=True, help_text='کاربری\u200cهایی که این ملک برای آنها مناسب است', null=True, related_name='properties', to='estate.usagetype', verbose_name='انواع کاربری ملک'),
        ),
    ]
