# Generated by Django 6.0.5 on 2026-07-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0011_usagetype_customer_preferred_usage_types_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, choices=[('available', 'موجود'), ('pending', 'در انتظار'), ('reserved', 'رزرو شده'), ('sold', 'فروخته شده'), ('rented', 'اجاره داده شده'), ('unavailable', 'ناموجود')], default='pending', max_length=20, null=True, verbose_name='وضعیت'),
        ),
    ]
