# Generated by Django 6.0.5 on 2026-07-13 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0012_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('deposit', 'بیعانه'), ('contract', 'قرارداد'), ('cancelled', 'کنسل شده')], default='pending', max_length=20, null=True, verbose_name='وضعیت'),
        ),
    ]
