# Generated by Django 6.0.5 on 2026-07-13 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0013_alter_property_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'در انتظار بررسی'), ('confirmed', 'تایید شده'), ('assigned', 'ارجاع شده'), ('waiting', 'در انتظار تصمیم'), ('deposit', 'بیعانه'), ('contract', 'قرارداد'), ('cancelled', 'کنسل شده')], default='new', max_length=20, null=True, verbose_name='وضعیت'),
        ),
    ]
