# Generated by Django 6.0.5 on 2026-07-14 14:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0014_alter_customer_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_experted', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس'),
        ),
        migrations.AddField(
            model_name='customer',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_supervised', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست'),
        ),
        migrations.AddField(
            model_name='property',
            name='expert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_experted', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس'),
        ),
        migrations.AddField(
            model_name='property',
            name='supervisor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='properties_supervised', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست'),
        ),
    ]
