# Generated by Django 6.0.5 on 2026-07-14 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0015_customer_expert_customer_supervisor_property_expert_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DuplicateCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_type', models.CharField(choices=[('customer', 'مشتری'), ('property', 'ملک')], max_length=10, verbose_name='نوع بررسی')),
                ('check_id', models.UUIDField(blank=True, null=True, verbose_name='شناسه مورد بررسی')),
                ('duplicate_ids', models.JSONField(default=list, verbose_name='شناسه\u200cهای تکراری')),
                ('duplicate_data', models.JSONField(default=dict, verbose_name='داده\u200cهای تکراری')),
                ('similarity_score', models.FloatField(default=0, verbose_name='امتیاز تشابه')),
                ('match_details', models.JSONField(blank=True, default=dict, verbose_name='جزئیات تطابق')),
                ('status', models.CharField(choices=[('pending', 'در انتظار بررسی'), ('confirmed', 'تکراری تایید شد'), ('rejected', 'تکراری رد شد'), ('false', 'تکراری نیست')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('reviewer_note', models.TextField(blank=True, null=True, verbose_name='یادداشت بررسی\u200cکننده')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ بررسی')),
                ('checked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='duplicate_checks', to=settings.AUTH_USER_MODEL, verbose_name='بررسی\u200cکننده')),
            ],
            options={
                'verbose_name': 'بررسی تکراری',
                'verbose_name_plural': 'بررسی\u200cهای تکراری',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['check_type', 'check_id'], name='estate_dupl_check_t_b27fd6_idx'), models.Index(fields=['status'], name='estate_dupl_status_121af5_idx')],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('general', 'یادداشت عمومی'), ('customer', 'یادداشت مشتری'), ('property', 'یادداشت ملک'), ('important', 'نکته مهم'), ('warning', 'هشدار'), ('review', 'نظر کارشناسی')], default='general', max_length=20, verbose_name='نوع یادداشت')),
                ('priority', models.CharField(choices=[('low', 'کم'), ('medium', 'متوسط'), ('high', 'بالا'), ('urgent', 'فوری')], default='medium', max_length=10, verbose_name='اولویت')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(verbose_name='متن یادداشت')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='برطرف شده')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ برطرف شدن')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ سررسید')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_assigned', to=settings.AUTH_USER_MODEL, verbose_name='اختصاص داده شده به')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_created', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='estate.customer', verbose_name='مشتری مرتبط')),
                ('property_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='estate.property', verbose_name='ملک مرتبط')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes_resolved', to=settings.AUTH_USER_MODEL, verbose_name='برطرف کننده')),
            ],
            options={
                'verbose_name': 'یادداشت',
                'verbose_name_plural': 'یادداشت\u200cها',
                'ordering': ['-priority', '-created_at'],
                'indexes': [models.Index(fields=['customer', 'is_resolved'], name='estate_note_custome_898232_idx'), models.Index(fields=['property_ref', 'is_resolved'], name='estate_note_propert_6927cb_idx'), models.Index(fields=['assigned_to', 'is_resolved'], name='estate_note_assigne_4fc47e_idx'), models.Index(fields=['priority'], name='estate_note_priorit_16efcc_idx')],
            },
        ),
    ]
