# Generated by Django 6.0.5 on 2026-07-16 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0016_duplicatecheck_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='introduction_confirmed',
            field=models.BooleanField(default=False, verbose_name='تایید شده توسط سرپرست؟'),
        ),
        migrations.AddField(
            model_name='match',
            name='introduction_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='تاریخ تایید'),
        ),
        migrations.AddField(
            model_name='match',
            name='introduction_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_introductions', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده (سرپرست)'),
        ),
        migrations.AddField(
            model_name='match',
            name='introduction_note',
            field=models.TextField(blank=True, help_text='توضیح کارشناس درباره علت موفقیت یا عدم موفقیت معرفی', null=True, verbose_name='یادداشت معرفی'),
        ),
        migrations.AddField(
            model_name='match',
            name='introduction_status',
            field=models.CharField(choices=[('pending', 'در انتظار معرفی'), ('success', 'معرفی موفق (مشتری علاقه\u200cمند شد)'), ('fail', 'معرفی ناموفق (مشتری علاقه\u200cای نداشت)'), ('not_applicable', 'قابل معرفی نیست')], default='pending', help_text='نتیجه معرفی این فایل به مشتری', max_length=20, verbose_name='وضعیت معرفی'),
        ),
        migrations.AddIndex(
            model_name='match',
            index=models.Index(fields=['introduction_status', 'introduction_confirmed'], name='estate_matc_introdu_5fb3cf_idx'),
        ),
    ]
