# Generated by Django 6.0.5 on 2026-07-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0017_match_introduction_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='status',
            field=models.CharField(blank=True, choices=[('new', 'در انتظار بررسی'), ('confirmed', 'تایید شده'), ('assigned', 'ارجاع شده'), ('waiting', 'در انتظار تصمیم'), ('deposit', 'بیعانه'), ('in_meeting', 'در جلسه مذاکره'), ('contract', 'قرارداد'), ('cancelled', 'کنسل شده')], default='new', max_length=20, null=True, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='property',
            name='status',
            field=models.CharField(blank=True, choices=[('pending', 'در انتظار'), ('confirmed', 'تایید شده'), ('deposit', 'بیعانه'), ('in_meeting', 'در جلسه مذاکره'), ('contract', 'قرارداد'), ('cancelled', 'کنسل شده')], default='pending', max_length=20, null=True, verbose_name='وضعیت'),
        ),
    ]
