# Generated by Django 6.0.5 on 2026-07-28 21:53

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0018_alter_customer_status_alter_property_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام نوع سند')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد نوع سند')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'نوع سند',
                'verbose_name_plural': 'انواع سند',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Orientation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام جهت')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد جهت')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='آیکون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'جهت',
                'verbose_name_plural': 'جهت\u200cها',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OwnershipDocumentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام نوع مالکیت سند')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد نوع مالکیت سند')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'نوع مالکیت سند',
                'verbose_name_plural': 'انواع مالکیت سند',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='UnitCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نام وضعیت')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='کد وضعیت')),
                ('icon', models.CharField(blank=True, max_length=50, null=True, verbose_name='آیکون')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ترتیب نمایش')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
            ],
            options={
                'verbose_name': 'وضعیت واحد',
                'verbose_name_plural': 'وضعیت\u200cهای واحد',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.RemoveField(
            model_name='property',
            name='furnishing_status',
        ),
        migrations.AddField(
            model_name='customer',
            name='need_completion_certificate',
            field=models.BooleanField(default=False, verbose_name='نیاز به پایان کار دارد؟'),
        ),
        migrations.AddField(
            model_name='customer',
            name='need_document',
            field=models.BooleanField(default=False, verbose_name='نیاز به سند دارد؟'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_dong_max',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='حداکثر دانگ مورد نظر (۱ تا ۶)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_dong_min',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='حداقل دانگ مورد نظر (۱ تا ۶)'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_max_floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='حداکثر طبقه مورد نظر'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_max_total_floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='حداکثر تعداد طبقات ساختمان'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_max_units_per_floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='حداکثر تعداد واحد در طبقه'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_min_floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='حداقل طبقه مورد نظر'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_min_total_floors',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='حداقل تعداد طبقات ساختمان'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_min_units_per_floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='حداقل تعداد واحد در طبقه'),
        ),
        migrations.AddField(
            model_name='customer',
            name='primary_usage',
            field=models.ForeignKey(blank=True, help_text='کاربری اصلی و سندی که مشتری به دنبال آن است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customers_primary', to='estate.usagetype', verbose_name='کاربری سندی مورد نظر'),
        ),
        migrations.AddField(
            model_name='property',
            name='dong',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)], verbose_name='میزان دانگ (۱ تا ۶)'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_completion_certificate',
            field=models.BooleanField(default=False, verbose_name='دارای پایان کار'),
        ),
        migrations.AddField(
            model_name='property',
            name='has_document',
            field=models.BooleanField(default=False, verbose_name='دارای سند'),
        ),
        migrations.AddField(
            model_name='property',
            name='units_per_floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='تعداد واحد در طبقه'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_usage_types',
            field=models.ManyToManyField(blank=True, help_text='کاربری\u200cهایی که مشتری به آنها علاقه دارد (کاربردهای فرعی)', null=True, related_name='customers_preferred', to='estate.usagetype', verbose_name='کاربردهای مورد نظر'),
        ),
        migrations.AlterField(
            model_name='property',
            name='primary_usage',
            field=models.ForeignKey(blank=True, help_text='کاربری اصلی و سند این ملک', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='primary_properties', to='estate.usagetype', verbose_name='کاربری سندی (اصلی)'),
        ),
        migrations.AlterField(
            model_name='property',
            name='usage_types',
            field=models.ManyToManyField(blank=True, help_text='کاربری\u200cهایی که این ملک برای آنها مناسب است (کاربردهای فرعی)', null=True, related_name='properties', to='estate.usagetype', verbose_name='کاربردهای ملک'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_document_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='customers', to='estate.documenttype', verbose_name='انواع سند مورد نظر'),
        ),
        migrations.AddField(
            model_name='property',
            name='document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='estate.documenttype', verbose_name='نوع سند'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_building_orientations',
            field=models.ManyToManyField(blank=True, null=True, related_name='customers_building', to='estate.orientation', verbose_name='جهت\u200cهای ساختمان مورد نظر'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_unit_orientations',
            field=models.ManyToManyField(blank=True, null=True, related_name='customers_unit', to='estate.orientation', verbose_name='جهت\u200cهای واحد مورد نظر'),
        ),
        migrations.AddField(
            model_name='property',
            name='building_orientation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties_building', to='estate.orientation', verbose_name='جهت ساختمان'),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_orientation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties_unit', to='estate.orientation', verbose_name='جهت واحد'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_ownership_document_types',
            field=models.ManyToManyField(blank=True, null=True, related_name='customers', to='estate.ownershipdocumenttype', verbose_name='انواع مالکیت سند مورد نظر'),
        ),
        migrations.AddField(
            model_name='property',
            name='ownership_document_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='estate.ownershipdocumenttype', verbose_name='نوع مالکیت سند'),
        ),
        migrations.AddField(
            model_name='customer',
            name='preferred_unit_conditions',
            field=models.ManyToManyField(blank=True, null=True, related_name='customers', to='estate.unitcondition', verbose_name='وضعیت\u200cهای واحد مورد نظر'),
        ),
        migrations.AddField(
            model_name='property',
            name='unit_condition',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='properties', to='estate.unitcondition', verbose_name='وضعیت واحد'),
        ),
    ]
