# Generated by Django 6.0.5 on 2026-07-28 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0019_documenttype_orientation_ownershipdocumenttype_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisplayCodeCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('customer', 'مشتری'), ('property', 'ملک')], max_length=10, unique=True, verbose_name='نوع')),
                ('last_number', models.PositiveIntegerField(default=0, verbose_name='آخرین عدد اختصاص\u200cیافته')),
            ],
            options={
                'verbose_name': 'شمارنده کد نمایشی',
                'verbose_name_plural': 'شمارنده\u200cهای کد نمایشی',
            },
        ),
        migrations.AddField(
            model_name='customer',
            name='display_code',
            field=models.CharField(blank=True, help_text='فرمت: C-XXXXX (عدد ترتیبی ۵ رقمی)', max_length=20, null=True, verbose_name='کد نمایشی مشتری'),
        ),
        migrations.AddField(
            model_name='property',
            name='display_code',
            field=models.CharField(blank=True, help_text='فرمت: P-XXXXX (عدد ترتیبی ۵ رقمی)', max_length=20, null=True, verbose_name='کد نمایشی ملک'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_building_orientations',
            field=models.ManyToManyField(blank=True, related_name='customers_building', to='estate.orientation', verbose_name='جهت\u200cهای ساختمان مورد نظر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_cities',
            field=models.ManyToManyField(blank=True, related_name='customers_preferred', to='estate.city', verbose_name='شهرهای مورد نظر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_document_types',
            field=models.ManyToManyField(blank=True, related_name='customers', to='estate.documenttype', verbose_name='انواع سند مورد نظر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_neighborhoods',
            field=models.ManyToManyField(blank=True, related_name='customers_preferred', to='estate.neighborhood', verbose_name='محله\u200cهای مورد نظر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_ownership_document_types',
            field=models.ManyToManyField(blank=True, related_name='customers', to='estate.ownershipdocumenttype', verbose_name='انواع مالکیت سند مورد نظر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_property_types',
            field=models.ManyToManyField(blank=True, related_name='customers_preferred', to='estate.propertytype', verbose_name='انواع ملک مورد نظر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_requirements',
            field=models.ManyToManyField(blank=True, help_text='امکاناتی که مشتری در ملک مورد نظر خود می\u200cخواهد', related_name='customers_preferred', to='estate.requirement', verbose_name='نیازهای خاص مورد نظر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_unit_conditions',
            field=models.ManyToManyField(blank=True, related_name='customers', to='estate.unitcondition', verbose_name='وضعیت\u200cهای واحد مورد نظر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_unit_orientations',
            field=models.ManyToManyField(blank=True, related_name='customers_unit', to='estate.orientation', verbose_name='جهت\u200cهای واحد مورد نظر'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='preferred_usage_types',
            field=models.ManyToManyField(blank=True, help_text='کاربری\u200cهایی که مشتری به آنها علاقه دارد (کاربردهای فرعی)', related_name='customers_preferred', to='estate.usagetype', verbose_name='کاربردهای مورد نظر'),
        ),
        migrations.AlterField(
            model_name='property',
            name='requirements',
            field=models.ManyToManyField(blank=True, related_name='properties', to='estate.requirement', verbose_name='امکانات ملک'),
        ),
        migrations.AlterField(
            model_name='property',
            name='usage_types',
            field=models.ManyToManyField(blank=True, help_text='کاربری\u200cهایی که این ملک برای آنها مناسب است (کاربردهای فرعی)', related_name='properties', to='estate.usagetype', verbose_name='کاربردهای ملک'),
        ),
    ]
