# Generated by Django 6.0.5 on 2026-07-28 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0020_displaycodecounter_customer_display_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('buyer', 'خریدار'), ('tenant', 'مستاجر'), ('pre_buyer', 'پیش خریدار'), ('developer', 'سازنده'), ('investor', 'سرمایه\u200cگذار'), ('all', 'همه موارد')], default='buyer', max_length=20, null=True, verbose_name='نوع مشتری'),
        ),
        migrations.AlterField(
            model_name='property',
            name='contract_type',
            field=models.CharField(blank=True, choices=[('sale', 'فروش'), ('rent', 'اجاره'), ('pre_sale', 'پیش فروش'), ('both', 'فروش و اجاره'), ('partnership', 'مشارکت در ساخت'), ('investment', 'جذب سرمایه')], default='sale', max_length=20, null=True, verbose_name='نوع قرارداد'),
        ),
    ]
