# Generated by Django 6.0.5 on 2026-09-08 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0021_alter_customer_customer_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='showcase_image',
            field=models.ImageField(blank=True, help_text='تصویر ویژه و محرمانه ملک - فقط کاربران مجاز می\u200cتوانند آن را مشاهده کنند', null=True, upload_to='properties/showcase/%Y/%m/', verbose_name='تصویر نما'),
        ),
    ]
