# Generated by Django 6.0.5 on 2026-09-10 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0022_property_showcase_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='price_per_meter',
            field=models.DecimalField(blank=True, decimal_places=0, help_text='قیمت هر متر مربع ملک', max_digits=15, null=True, verbose_name='قیمت هر متر (تومان)'),
        ),
    ]
