# Generated by Django 6.0.5 on 2026-09-26 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estate', '0023_property_price_per_meter'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='is_rent_convertible',
            field=models.BooleanField(default=False, verbose_name='رهن و اجاره قابل تبدیل'),
        ),
    ]
