# Generated by Django 6.0.5 on 2026-07-15 13:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('estate', '0016_duplicatecheck_note'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerProcess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('status', models.CharField(choices=[('assigned', 'اختصاص داده شده'), ('contact_pending', 'نیاز به تماس'), ('contacted', 'تماس گرفته شده'), ('intro_pending', 'در انتظار معرفی'), ('introduced', 'معرفی انجام شد'), ('visit_pending', 'در انتظار درخواست بازدید'), ('visit_scheduled', 'بازدید برنامه\u200cریزی شد'), ('visit_done', 'بازدید انجام شد'), ('negotiation', 'جلسه مذاکره'), ('closed_success', 'بسته شده (موفق)'), ('closed_fail', 'بسته شده (ناموفق)'), ('cancelled', 'لغو شده توسط مشتری')], default='assigned', max_length=30, verbose_name='وضعیت')),
                ('assigned_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان اختصاص')),
                ('contact_made_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تماس')),
                ('introduction_completed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تکمیل معرفی')),
                ('contact_deadline', models.DateTimeField(blank=True, null=True, verbose_name='مهلت تماس (۲۴ ساعت)')),
                ('intro_deadline', models.DateTimeField(blank=True, null=True, verbose_name='مهلت معرفی (۲۴ ساعت پس از تماس)')),
                ('visit_result_deadline', models.DateTimeField(blank=True, null=True, verbose_name='مهلت ثبت نتیجه بازدید (۲۴ ساعت)')),
                ('missed_contact_reported', models.BooleanField(default=False)),
                ('missed_intro_reported', models.BooleanField(default=False)),
                ('missed_visit_result_reported', models.BooleanField(default=False)),
                ('final_result', models.TextField(blank=True, null=True, verbose_name='نتیجه نهایی')),
                ('is_successful', models.BooleanField(default=False, verbose_name='موفقیت آمیز؟')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بسته شدن')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='estate.customer', verbose_name='مشتری')),
                ('expert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes_as_expert', to=settings.AUTH_USER_MODEL, verbose_name='کارشناس')),
                ('supervisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes_as_supervisor', to=settings.AUTH_USER_MODEL, verbose_name='سرپرست')),
            ],
            options={
                'verbose_name': 'فرآیند مشتری',
                'verbose_name_plural': 'فرآیندهای مشتری',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='IntroductionReport',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('result', models.CharField(choices=[('success', 'موفق (مشتری علاقه\u200cمند شد)'), ('fail', 'ناموفق (مشتری علاقه\u200cای نداشت)'), ('pending', 'در انتظار پاسخ مشتری')], default='pending', max_length=10, verbose_name='نتیجه')),
                ('expert_note', models.TextField(blank=True, help_text='توضیح دهید چرا مشتری علاقه\u200cمند شد یا نشد', verbose_name='توضیح کارشناس')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introduction_reports', to='case_management.customerprocess', verbose_name='فرآیند')),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='introduction_reports', to='estate.property', verbose_name='ملک معرفی شده')),
            ],
            options={
                'verbose_name': 'گزارش معرفی',
                'verbose_name_plural': 'گزارش\u200cهای معرفی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('action', models.CharField(choices=[('status_change', 'تغییر وضعیت'), ('contact_made', 'تماس گرفته شد'), ('intro_reported', 'گزارش معرفی ثبت شد'), ('visit_requested', 'درخواست بازدید'), ('visit_scheduled', 'برنامه\u200cریزی بازدید'), ('visit_done', 'بازدید انجام شد'), ('visit_cancelled', 'لغو بازدید'), ('negotiation_requested', 'درخواست جلسه مذاکره'), ('process_closed', 'بسته شدن فرآیند'), ('deadline_warning', 'اخطار مهلت')], max_length=30, verbose_name='نوع اقدام')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('old_value', models.CharField(blank=True, max_length=100, null=True)),
                ('new_value', models.CharField(blank=True, max_length=100, null=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_logs', to=settings.AUTH_USER_MODEL, verbose_name='انجام\u200cدهنده')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='case_management.customerprocess', verbose_name='فرآیند')),
            ],
            options={
                'verbose_name': 'لاگ فعالیت',
                'verbose_name_plural': 'لاگ\u200cهای فعالیت',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupervisorAlert',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('alert_type', models.CharField(choices=[('missed_contact', 'عدم تماس در مهلت مقرر'), ('missed_introduction', 'عدم معرفی کامل در مهلت'), ('missed_visit_result', 'عدم ثبت نتیجه بازدید'), ('visit_reminder', 'یادآوری بازدید امروز')], max_length=30, verbose_name='نوع اخطار')),
                ('message', models.TextField(verbose_name='متن اخطار')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده؟')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان خواندن')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='case_management.customerprocess', verbose_name='فرآیند مرتبط')),
            ],
            options={
                'verbose_name': 'اخطار به سرپرست',
                'verbose_name_plural': 'اخطارهای سرپرست',
                'ordering': ['-created_at', 'is_read'],
            },
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='شناسه یکتا')),
                ('status', models.CharField(choices=[('requested', 'درخواست شده'), ('scheduled', 'برنامه\u200cریزی شده'), ('confirmed', 'تأیید نهایی (روز بازدید)'), ('done', 'انجام شد'), ('cancelled', 'لغو شد')], default='requested', max_length=20, verbose_name='وضعیت')),
                ('requested_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان درخواست')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='زمان برنامه\u200cریزی شده')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان تأیید نهایی')),
                ('done_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انجام بازدید')),
                ('visit_result', models.TextField(blank=True, null=True, verbose_name='نتیجه بازدید')),
                ('negotiation_requested', models.BooleanField(default=False, verbose_name='آیا به جلسه مذاکره رسید؟')),
                ('negotiation_scheduled', models.BooleanField(default=False, verbose_name='آیا جلسه مذاکره هماهنگ شد؟')),
                ('reminder_sent', models.BooleanField(default=False, verbose_name='یادآوری ارسال شد')),
                ('negotiation_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_visits', to=settings.AUTH_USER_MODEL, verbose_name='مدیر جلسه مذاکره')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='case_management.customerprocess', verbose_name='فرآیند')),
                ('property_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='estate.property', verbose_name='ملک مورد بازدید')),
            ],
            options={
                'verbose_name': 'بازدید',
                'verbose_name_plural': 'بازدیدها',
                'ordering': ['-scheduled_time', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='customerprocess',
            index=models.Index(fields=['status', 'expert'], name='case_manage_status_41199b_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprocess',
            index=models.Index(fields=['status', 'supervisor'], name='case_manage_status_c0aeb6_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprocess',
            index=models.Index(fields=['contact_deadline'], name='case_manage_contact_b71d45_idx'),
        ),
        migrations.AddIndex(
            model_name='customerprocess',
            index=models.Index(fields=['intro_deadline'], name='case_manage_intro_d_7f756b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='introductionreport',
            unique_together={('process', 'property_ref')},
        ),
    ]
