# Generated by Django 6.0.5 on 2026-07-15 15:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note_type', models.CharField(choices=[('contact_report', 'گزارش تماس'), ('general', 'یادداشت عمومی'), ('important', 'نکته مهم')], default='general', max_length=20, verbose_name='نوع نت')),
                ('content', models.TextField(verbose_name='متن نت')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان ثبت')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='process_notes', to=settings.AUTH_USER_MODEL, verbose_name='نویسنده')),
                ('process', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='case_management.customerprocess', verbose_name='فرآیند')),
            ],
            options={
                'verbose_name': 'نت فرآیند',
                'verbose_name_plural': 'نت\u200cهای فرآیند',
                'ordering': ['-created_at'],
            },
        ),
    ]
