# Generated by Django 6.0.5 on 2026-07-15 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0002_processnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='processnote',
            name='target',
            field=models.CharField(choices=[('public', 'عمومی'), ('supervisor', 'سرپرست'), ('callcenter', 'کال سنتر')], default='public', max_length=20, verbose_name='مخاطب'),
        ),
    ]
