# Generated by Django 6.0.5 on 2026-07-15 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0003_processnote_target'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='processnote',
            name='confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان تایید'),
        ),
        migrations.AddField(
            model_name='processnote',
            name='confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_notes', to=settings.AUTH_USER_MODEL, verbose_name='تایید کننده'),
        ),
        migrations.AddField(
            model_name='processnote',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='تایید شده توسط کال سنتر'),
        ),
    ]
