# Generated by Django 6.0.5 on 2026-07-16 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0004_processnote_confirmed_at_processnote_confirmed_by_and_more'),
        ('estate', '0017_match_introduction_confirmed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='introductionreport',
            name='follow_up_date',
            field=models.DateTimeField(blank=True, help_text='اگر نیاز به تماس مجدد است، زمان آن را مشخص کنید', null=True, verbose_name='زمان پیگیری بعدی'),
        ),
        migrations.AddIndex(
            model_name='introductionreport',
            index=models.Index(fields=['follow_up_date'], name='case_manage_follow__69ad1f_idx'),
        ),
    ]
