# Generated by Django 6.0.5 on 2026-07-17 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0005_introductionreport_follow_up_date_and_more'),
        ('estate', '0017_match_introduction_confirmed_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='introductionreport',
            unique_together=set(),
        ),
        migrations.AddIndex(
            model_name='introductionreport',
            index=models.Index(fields=['process', 'property_ref'], name='case_manage_process_be52af_idx'),
        ),
    ]
