# Generated by Django 6.0.5 on 2026-07-18 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0006_alter_introductionreport_unique_together_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprocess',
            name='close_note',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات بسته شدن'),
        ),
        migrations.AddField(
            model_name='customerprocess',
            name='close_reason',
            field=models.CharField(blank=True, choices=[('contract', 'تبدیل به قرارداد'), ('cancelled_by_customer', 'کنسل توسط مشتری'), ('cancelled_by_expert', 'کنسل توسط کارشناس'), ('not_interested', 'مشتری علاقه\u200cای نداشت'), ('price_mismatch', 'عدم تطابق قیمت'), ('other', 'سایر')], max_length=30, null=True, verbose_name='دلیل بسته شدن'),
        ),
        migrations.AddField(
            model_name='customerprocess',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_processes', to=settings.AUTH_USER_MODEL, verbose_name='بسته کننده'),
        ),
        migrations.AddField(
            model_name='visit',
            name='meeting_held_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='زمان برگزاری جلسه'),
        ),
        migrations.AddField(
            model_name='visit',
            name='meeting_note',
            field=models.TextField(blank=True, help_text='یادداشت\u200cهای تکمیلی جلسه', null=True, verbose_name='یادداشت جلسه'),
        ),
        migrations.AddField(
            model_name='visit',
            name='meeting_result',
            field=models.TextField(blank=True, help_text='نتیجه جلسه مذاکره که توسط مدیر جلسه ثبت می\u200cشود', null=True, verbose_name='نتیجه جلسه مذاکره'),
        ),
        migrations.AddField(
            model_name='visit',
            name='meeting_result_confirmed',
            field=models.BooleanField(default=False, verbose_name='نتیجه جلسه تایید شده؟'),
        ),
        migrations.AddField(
            model_name='visit',
            name='meeting_status',
            field=models.CharField(choices=[('pending', 'در انتظار برگزاری'), ('held', 'برگزار شد'), ('cancelled', 'لغو شد'), ('postponed', 'به تعویق افتاد')], default='pending', max_length=20, verbose_name='وضعیت برگزاری جلسه'),
        ),
        migrations.AlterField(
            model_name='customerprocess',
            name='status',
            field=models.CharField(choices=[('assigned', 'اختصاص داده شده'), ('contact_pending', 'نیاز به تماس'), ('contacted', 'تماس گرفته شده'), ('intro_pending', 'در انتظار معرفی'), ('introduced', 'معرفی انجام شد'), ('visit_pending', 'در انتظار درخواست بازدید'), ('visit_scheduled', 'بازدید برنامه\u200cریزی شد'), ('visit_done', 'بازدید انجام شد'), ('negotiation', 'جلسه مذاکره'), ('closed_success', 'بسته شده (موفق)'), ('closed_fail', 'بسته شده (ناموفق)'), ('cancelled', 'لغو شده توسط مشتری'), ('converted', 'تبدیل به قرارداد')], default='assigned', max_length=30, verbose_name='وضعیت'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='negotiation_manager',
            field=models.ForeignKey(blank=True, help_text='کاربری با نقش meetingchair که مسئول برگزاری جلسه مذاکره است', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_visits', to=settings.AUTH_USER_MODEL, verbose_name='مدیر جلسه مذاکره'),
        ),
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('requested', 'درخواست شده'), ('scheduled', 'برنامه\u200cریزی شده'), ('confirmed', 'تأیید نهایی (روز بازدید)'), ('done', 'انجام شد'), ('cancelled', 'لغو شد'), ('postponed', 'به تعویق افتاد')], default='requested', max_length=20, verbose_name='وضعیت'),
        ),
    ]
