# Generated by Django 6.0.5 on 2026-07-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0008_alter_customerprocess_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerprocess',
            name='status',
            field=models.CharField(choices=[('assigned', 'اختصاص داده شده'), ('contact_pending', 'نیاز به تماس'), ('contacted', 'تماس گرفته شده'), ('intro_pending', 'در انتظار معرفی'), ('introduced', 'معرفی انجام شد'), ('visit_pending', 'در انتظار درخواست بازدید'), ('visit_scheduled', 'بازدید برنامه\u200cریزی شد'), ('visit_done', 'بازدید انجام شد'), ('negotiation', 'جلسه مذاکره'), ('contract_pending', 'در انتظار تنظیم قرارداد'), ('sent_to_accounting', 'ارسال به حسابداری'), ('closed_success', 'بسته شده (موفق)'), ('closed_fail', 'بسته شده (ناموفق)'), ('cancelled', 'لغو شده توسط مشتری'), ('converted', 'تبدیل به قرارداد')], default='assigned', max_length=30, verbose_name='وضعیت'),
        ),
    ]
