# Generated by Django 6.0.5 on 2026-07-19 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('case_management', '0009_alter_customerprocess_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processlog',
            name='action',
            field=models.CharField(choices=[('status_change', 'تغییر وضعیت'), ('contact_made', 'تماس گرفته شد'), ('intro_reported', 'گزارش معرفی ثبت شد'), ('visit_requested', 'درخواست بازدید'), ('visit_scheduled', 'برنامه\u200cریزی بازدید'), ('visit_done', 'بازدید انجام شد'), ('visit_cancelled', 'لغو بازدید'), ('negotiation_requested', 'درخواست جلسه مذاکره'), ('process_closed', 'بسته شدن فرآیند'), ('deadline_warning', 'اخطار مهلت'), ('withdrawal_request', 'Withdrawal Request')], max_length=30, verbose_name='نوع اقدام'),
        ),
        migrations.AlterField(
            model_name='processlog',
            name='process',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='case_management.customerprocess', verbose_name='فرآیند'),
        ),
    ]
