# Generated by Django 6.0.5 on 2026-07-06 13:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('form_flow', '0006_alter_forminstance_deadline_hours'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rejection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('field', 'سطح فیلد'), ('step', 'سطح مرحله'), ('form', 'سطح کل فرم')], max_length=10)),
                ('step_number', models.PositiveIntegerField(blank=True, null=True)),
                ('reason', models.TextField(verbose_name='دلیل برگشت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار اصلاح'), ('responded', 'پاسخ داده شده'), ('fixed', 'اصلاح شده'), ('rejected_again', 'دوباره برگشت خورده'), ('approved', 'تایید شده'), ('expired', 'منقضی شده')], default='pending', max_length=20)),
                ('deadline_hours', models.PositiveIntegerField(default=48)),
                ('deadline_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections_assigned', to=settings.AUTH_USER_MODEL)),
                ('form_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rejections', to='form_flow.forminstance')),
                ('instance_field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections', to='form_flow.instancefield')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_rejections', to='form_review.rejection')),
                ('rejected_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rejections_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'برگشت فرم',
                'verbose_name_plural': 'برگشت\u200cهای فرم',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RejectionReply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='متن پاسخ')),
                ('reply_type', models.CharField(choices=[('response', 'پاسخ به برگشت'), ('clarification', 'درخواست توضیح بیشتر'), ('approve', 'تایید'), ('reject_again', 'برگشت مجدد'), ('fix', 'اصلاح شد')], default='response', max_length=20)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='rejection_attachments/%Y/%m/%d/', verbose_name='فایل ضمیمه')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('rejection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='form_review.rejection')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'پاسخ به برگشت',
                'verbose_name_plural': 'پاسخ\u200cهای برگشت',
                'ordering': ['created_at'],
            },
        ),
    ]
