# Generated by Django 6.0.5 on 2026-06-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Excel_export',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('export_name', models.CharField(blank=True, max_length=10, null=True)),
                ('export_date', models.DateField(blank=True, null=True)),
                ('start_rows', models.IntegerField(blank=True, null=True)),
                ('end_rows', models.IntegerField(blank=True, null=True)),
                ('file_url', models.CharField(blank=True, max_length=200, null=True)),
                ('file', models.FileField(upload_to='excel_files/')),
            ],
        ),
        migrations.CreateModel(
            name='State_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(blank=True, max_length=70, null=True)),
                ('city', models.TextField(blank=True, max_length=4000, null=True)),
            ],
        ),
    ]
