# Generated by Django 6.0.5 on 2026-07-11 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_profile', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Excel_export',
        ),
        migrations.DeleteModel(
            name='State_city',
        ),
    ]
